"""Add SaveData table

Revision ID: b227af5c3e94
Revises: 
Create Date: 2025-07-01 21:14:15.852952

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'b227af5c3e94'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_name', sa.String(length=100), nullable=True),
    sa.Column('from_email', sa.String(length=120), nullable=True),
    sa.Column('subject', sa.String(length=200), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('priority', sa.String(length=50), nullable=True),
    sa.Column('read_status', sa.Boolean(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(length=50), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('participants_affected', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hackathon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('npc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('role', sa.String(length=100), nullable=True),
    sa.Column('personality', sa.Text(), nullable=True),
    sa.Column('last_interaction', sa.DateTime(timezone=True), nullable=True),
    sa.Column('memory_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('participant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('github_username', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('stress_level', sa.Integer(), nullable=True),
    sa.Column('commit_count', sa.Integer(), nullable=True),
    sa.Column('devlog_count', sa.Integer(), nullable=True),
    sa.Column('housing_status', sa.String(length=50), nullable=True),
    sa.Column('housing_id', sa.Integer(), nullable=True),
    sa.Column('stipend_amount', sa.Float(), nullable=True),
    sa.Column('flight_status', sa.String(length=50), nullable=True),
    sa.Column('last_active', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('hackathon_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hackathon_id'], ['hackathon.id'], ),
    sa.ForeignKeyConstraint(['housing_id'], ['housing.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('save_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('last_saved', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('ai_npc')
    op.drop_table('task')
    op.drop_table('project_participant')
    op.drop_table('report')
    op.drop_table('message')
    op.drop_table('game')
    op.drop_table('inbox')
    with op.batch_alter_table('commit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('participant_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('repository', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('lines_added', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('lines_removed', sa.Integer(), nullable=True))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('message',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('timestamp',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'participant', ['participant_id'], ['id'])
        batch_op.drop_column('hash')
        batch_op.drop_column('project_id')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('devlog', schema=None) as batch_op:
        batch_op.add_column(sa.Column('participant_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('word_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('sentiment', sa.String(length=50), nullable=True))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('content',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('timestamp',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'participant', ['participant_id'], ['id'])
        batch_op.drop_column('project_id')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('flight', schema=None) as batch_op:
        batch_op.add_column(sa.Column('participant_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('departure_city', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('arrival_city', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('departure_date', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('return_date', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('estimated_cost', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('actual_cost', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('booking_reference', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'participant', ['participant_id'], ['id'])
        batch_op.drop_column('flight_number')
        batch_op.drop_column('airline')
        batch_op.drop_column('arrival_airport')
        batch_op.drop_column('user_id')
        batch_op.drop_column('departure_datetime')
        batch_op.drop_column('arrival_datetime')
        batch_op.drop_column('cost')
        batch_op.drop_column('departure_airport')
        batch_op.drop_column('project_id')

    with op.batch_alter_table('housing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('capacity', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('occupied_spots', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('lease_expiry', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('price_per_night', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('location', sa.String(length=200), nullable=True))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')
        batch_op.drop_column('cost')
        batch_op.drop_column('check_in_date')
        batch_op.drop_column('check_out_date')
        batch_op.drop_column('project_id')
        batch_op.drop_column('address')

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('participant_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('title', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('repository_url', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('completion_percentage', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_commit', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('shipping_status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'participant', ['participant_id'], ['id'])
        batch_op.drop_column('creator_id')
        batch_op.drop_column('name')
        batch_op.drop_column('budget')
        batch_op.drop_column('end_date')
        batch_op.drop_column('start_date')

    with op.batch_alter_table('receipt', schema=None) as batch_op:
        batch_op.add_column(sa.Column('participant_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('filename', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('category', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('ai_validation', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('flagged_reason', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('amount',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'participant', ['participant_id'], ['id'])
        batch_op.drop_column('purchase_date')
        batch_op.drop_column('user_id')
        batch_op.drop_column('store_name')
        batch_op.drop_column('project_id')
        batch_op.drop_column('image_url')
        batch_op.drop_column('item_name')

    with op.batch_alter_table('stipend', schema=None) as batch_op:
        batch_op.add_column(sa.Column('participant_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('justification', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('receipt_urls', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('approved_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('amount',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'participant', ['participant_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['approved_by'], ['id'])
        batch_op.drop_column('description')
        batch_op.drop_column('payment_date')
        batch_op.drop_column('project_id')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.create_unique_constraint(None, ['email'])
        batch_op.create_unique_constraint(None, ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('stipend', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('project_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('payment_date', sa.DATE(), nullable=False))
        batch_op.add_column(sa.Column('description', sa.TEXT(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'project', ['project_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.alter_column('amount',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
        batch_op.drop_column('created_at')
        batch_op.drop_column('approved_at')
        batch_op.drop_column('approved_by')
        batch_op.drop_column('status')
        batch_op.drop_column('receipt_urls')
        batch_op.drop_column('justification')
        batch_op.drop_column('participant_id')

    with op.batch_alter_table('receipt', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_name', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('image_url', sa.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('project_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('store_name', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('purchase_date', sa.DATE(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'project', ['project_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.alter_column('amount',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
        batch_op.drop_column('uploaded_at')
        batch_op.drop_column('flagged_reason')
        batch_op.drop_column('ai_validation')
        batch_op.drop_column('status')
        batch_op.drop_column('description')
        batch_op.drop_column('category')
        batch_op.drop_column('filename')
        batch_op.drop_column('participant_id')

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_date', sa.DATE(), nullable=False))
        batch_op.add_column(sa.Column('end_date', sa.DATE(), nullable=False))
        batch_op.add_column(sa.Column('budget', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('creator_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['creator_id'], ['id'])
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
        batch_op.drop_column('created_at')
        batch_op.drop_column('shipping_status')
        batch_op.drop_column('last_commit')
        batch_op.drop_column('completion_percentage')
        batch_op.drop_column('status')
        batch_op.drop_column('repository_url')
        batch_op.drop_column('title')
        batch_op.drop_column('participant_id')

    with op.batch_alter_table('housing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.VARCHAR(length=200), nullable=False))
        batch_op.add_column(sa.Column('project_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('check_out_date', sa.DATE(), nullable=False))
        batch_op.add_column(sa.Column('check_in_date', sa.DATE(), nullable=False))
        batch_op.add_column(sa.Column('cost', sa.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'project', ['project_id'], ['id'])
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
        batch_op.drop_column('location')
        batch_op.drop_column('price_per_night')
        batch_op.drop_column('lease_expiry')
        batch_op.drop_column('occupied_spots')
        batch_op.drop_column('capacity')
        batch_op.drop_column('description')
        batch_op.drop_column('title')

    with op.batch_alter_table('flight', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('departure_airport', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('cost', sa.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('arrival_datetime', sa.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('departure_datetime', sa.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('arrival_airport', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('airline', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('flight_number', sa.VARCHAR(length=20), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'project', ['project_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
        batch_op.drop_column('created_at')
        batch_op.drop_column('booking_reference')
        batch_op.drop_column('status')
        batch_op.drop_column('actual_cost')
        batch_op.drop_column('estimated_cost')
        batch_op.drop_column('return_date')
        batch_op.drop_column('departure_date')
        batch_op.drop_column('arrival_city')
        batch_op.drop_column('departure_city')
        batch_op.drop_column('participant_id')

    with op.batch_alter_table('devlog', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('project_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'project', ['project_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.alter_column('timestamp',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('content',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
        batch_op.drop_column('sentiment')
        batch_op.drop_column('word_count')
        batch_op.drop_column('participant_id')

    with op.batch_alter_table('commit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('project_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('hash', sa.VARCHAR(length=40), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'project', ['project_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.alter_column('timestamp',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('message',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
        batch_op.drop_column('lines_removed')
        batch_op.drop_column('lines_added')
        batch_op.drop_column('repository')
        batch_op.drop_column('participant_id')

    op.create_table('inbox',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('game_state', sqlite.JSON(), nullable=False),
    sa.Column('last_played', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('message',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('inbox_id', sa.INTEGER(), nullable=False),
    sa.Column('sender_id', sa.INTEGER(), nullable=False),
    sa.Column('recipient_id', sa.INTEGER(), nullable=False),
    sa.Column('subject', sa.VARCHAR(length=200), nullable=False),
    sa.Column('body', sa.TEXT(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_read', sa.BOOLEAN(), server_default=sa.text('0'), nullable=True),
    sa.ForeignKeyConstraint(['inbox_id'], ['inbox.id'], ),
    sa.ForeignKeyConstraint(['recipient_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('report',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('project_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_participant',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('project_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('role', sa.VARCHAR(length=50), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('project_id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=100), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('due_date', sa.DATE(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'To Do'"), nullable=True),
    sa.Column('assignee_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['assignee_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_npc',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('backstory', sa.TEXT(), nullable=True),
    sa.Column('personality', sa.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('save_data')
    op.drop_table('participant')
    op.drop_table('npc')
    op.drop_table('hackathon')
    op.drop_table('game_event')
    op.drop_table('email')
    # ### end Alembic commands ###
